wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1669754548
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 13
      4: 3.8.12
      5: 0.12.14
      8:
      - 5
